platform :ios, '11.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'ProfileScreenTest' do

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  # 3rd Party Pods for ProfileScreenTest
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  target 'ProfileScreenTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'ProfileScreenTest-tvOS' do
  # Pods for ProfileScreenTest-tvOS

  target 'ProfileScreenTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
